### ISSUE TITLE
Method to list existing endpoints

### ISSUE THREAD

**Issue by janakagamini** [jexp/cypher-rs#14]
Is there a way to get all the custom endpoints I have created? Something like:

    GET /cypher-rs

    --> 200
    [
        {
            "path": "actors",
            "cypher": "match (a:Actor) return a"
        },
        {
            "path": "movies",
            "cypher": "match (m:movie) return m"
        }
    ]

**Comment by jexp** [comment]
Yep, but I forgot to add it to the readme:

http://de.slideshare.net/neo4j/document-oriented-access-to-graphs
Slide 35 and 36

**Comment by janakagamini** [comment]
I tried this but I get:

    localhost:7474/cypher-rs
    --> 405 Method Not Allowed

and:

    localhost:7474/cypher-rs/my-endpoint/query
    --> 404 Not Found

I have verified that `my-endpoint` works though.

**Comment by jexp** [comment]
Probably a different branch. At least the commits where there.
Or I did forget to merge them, but I was sure I did.

https://github.com/justinoverton/cypher-rs/commit/55d16739779c23c64938927fe33ac2ee79ea54df

**Comment by jexp** [comment]
Merged now
