### ISSUE TITLE
Consistent JSON format for results containing single row and multiple rows

### ISSUE THREAD

**Issue by janakagamini** [jexp/cypher-rs#15]
I understand that each row of data returned from a query is represented in a JSON object and a query that returns multiple rows of data is an array of JSON objects like so:

    [
        {
            "name": "John",
            "age": 35
        },
        {
            "name": "Jane",
            "age": 18
        }
    ]

But it appears that a query that returns only 1 row of data is is not wrapped in an array and would look like:

    {
        "name": "John",
        "age": 35
    }

Given the same query in most cases it is impossible to know beforehand whether the return will be only 1 row of data or multiple rows of data. So with the current method it is a nightmare to parse the JSON, because I can't tell the parser whether to expect an array or a single object.

My suggestion (and what I have seen in other API's as a standard) is to always wrap the result in an array like so (even if the result had only 1 row):

    [
        {
            "name": "John",
            "age": 35
        }
    ]

**Comment by jexp** [comment]
Good point, I kind of thought it would be  nice to have the minimal decorum around the results but I think the consistency argument wins.

Feel free to send in an pull-request with the change, not sure when I get around to do it.

**Comment by janakagamini** [comment]
Hello, I made a pull-request. This is actually the first time I've done a pull-request. I'm quite new to Java, Git and Github so apologies in advance if I broke anything.

**Comment by jexp** [comment]
Merged PR manually.

**Comment by jexp** [comment]
Thanks a lot!!
